### PR TITLE
Added some needed files

### PR DESCRIPTION
**Pull request by alyh**
You need this if you want to use WebWorks. If you use PhoneGap at the same time, you should probably but this in a separate branch because they read the same config.xml file but look for different things.

Oh and you can probably change the author name.. probably. Just leave the ID.

### CODE REVIEW

**Comment by Eric-DeMone** [comment]
:octopus:

**Comment by Eric-DeMone** [comment]
:fried_shrimp:

**Comment by Eric-DeMone** [comment]
Hey

**Comment by Eric-DeMone** [comment]
Aly

**Comment by Eric-DeMone** [comment]
You should change your settings

**Comment by Eric-DeMone** [comment]
So you don't get emails

**Comment by Eric-DeMone** [comment]
Just a tip

**Comment by Eric-DeMone** [comment]
:D

**Comment by alyh** [comment]
I

**Comment by alyh** [comment]
think

**Comment by alyh** [comment]
I

**Comment by alyh** [comment]
will

**Comment by alyh** [comment]
offer :tangerine:

**Comment by alyh** [comment]
if

**Comment by alyh** [comment]
you

**Comment by alyh** [comment]
set it for me! :sailboat:

**Pull request closed without merging**
